import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";

import styles from "./styles.module.scss"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Bobyan Automation Tool</title>
        <script src="https://apis.google.com/js/platform.js" async defer />
        <meta name="google-signin-client_id" content="972701167072-mqonrb5linta1la5g41qc5drk2j2rktv.apps.googleusercontent.com" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["page-main"]}>
        <div className={styles["page-header"]}>Bobyan Automation - Floyd</div>
        <div className={styles["page-contents"]}>

        </div>
      </div>
    </>
  );
}
